### ISSUE TITLE
大佬，我执行后获取文档编号后就退出了

### ISSUE THREAD

**Issue by wyxiong431** [TinkerAC/BaiduDocumentDownloader#3]
& d:/Anaconda3/envs/sequoia39/python.exe d:/qlib/scripts/baidu.py
请检查文档ID:fdc9272856270722192e453610661ed9ac51555a
https://wenku.baidu.com/ndocview/readerinfo?docId=fdc9272856270722192e453610661ed9ac51555a&pn=100

**Comment by TinkerAC** [comment]
没办法，现在直接请求数据接口被反爬了，以后可能会考虑用Selenium写一个更好的，最近是没什么精力了

**Comment by wyxiong431** [comment]
谢大佬，已关注
